### ISSUE TITLE
VirusTotal result

### ISSUE THREAD

**Issue by darkj2k** [YoshifumiFuyuno/SPC-Native-Messaging-Host#1]
Is this normal? Windows Security also mark it as virus. I need spcnmh for external app function but...

[https://www.virustotal.com/gui/file/89d65ffc0dcf20fe25f13815585bd690789778b8ed5aef3a8828960bfe55fe6e/detection/f-89d65ffc0dcf20fe25f13815585bd690789778b8ed5aef3a8828960bfe55fe6e-1685709356](url)

**Comment by YoshifumiFuyuno** [comment]
Hi.
Thank you for reporting.

It's a false positive.
The exe is turned into an exe using [Nuitka](https://nuitka.net/) on GitHub Actions.
All sources for the exe conversion are below.
https://github.com/YoshifumiFuyuno/SPC-Native-Messaging-Host/blob/master/.github/workflows/build.yml

If you don't trust the exe version, install [Python](https://www.python.org/downloads/) and
You can use it by running `python setup.py` from a command prompt (for Windows), etc.
https://github.com/YoshifumiFuyuno/SPC-Native-Messaging-Host/tree/master#install-or-update
If you do not know how to install, please ask.

Best regards

**Comment by darkj2k** [comment]
Thanks for your info and now I feel comfortable. :-)
